### ISSUE TITLE
advanced Webview example : interaction with the webview DOM from PHONK script ?

### ISSUE THREAD

**Issue by SuperUserNameMan** [victordiaz/PHONK-examples#10]
Hello,

I don't know if it is possible. 

Here is the code I was testing :

````
i.addTitle(app.name)

function test()
{
    ui.toast("test!");
}

var webview = ui.addWebView(0.1, 0.1, 0.8, 0.25)

var content = '\
  <html> \
    <body style = "background: white">\
      <button onclick="app.test();">TEST</button>\
    </body>\
  </html>'
webview.loadData(content);

````

Question 1 : How to call ``test()`` from the webview ? 
Question 2 : How to manipulate the webview DOM from the PHONK script ?
Question 3 : I've seen that ``PWebView.java`` mention an ``.onTouchEvent()``, how do we use that in PHONK ?

**Comment by victordiaz** [comment]
Hi @SuperUserNameMan 

**Answer 1**
I think the following should work. 
```<button onclick="app.eval("test()");">TEST</button>```

Another option we can investigate is to have an user object where you can "hang" your custom functions and WebView can always add that object to the interface
So imagine we have an object such as `myfunctions` (name suggestions are welcomed) then adding a function will automatically be "exposed" to the WebView
```
myfunctions.test = function () {
}
```

**Answer 2**
If you use the WebView, then you have 2 Javascript runtimes working together. If you want to manipulate the DOM you should use the Javascript runtime from the WebView, the same as I you would do it in a normal Website.

**Answer 3**
The onTouchEvent is to allow scrolling the WebView within another scrolling element. It is activated by default.

**Comment by victordiaz** [comment]
I have to double check my answer, since nothing works 😅
I'll have a deeper look

**Comment by SuperUserNameMan** [comment]
> Answer 2
> If you use the WebView, then you have 2 Javascript runtimes working together. If you want to manipulate the DOM you should  use the Javascript runtime from the WebView, the same as I you would do it in a normal Website.

That makes sense indeed. Though, the general idea behind my questions is about how to create interactions between the 2 javascript runtimes.

What I was wondering was :
1) if it is possible to use the WebView to write UI.
2) if it was possible to embed an already existing HTML5 application or game into PHONK, and have some sort of access to PHONK functionalities from the WebView (or vice-versa) .

:-)

**Comment by victordiaz** [comment]
Hi @SuperUserNameMan 
Yes to 1 & 2 :)

Give me a couple of days to fix the issue and I push a new version of PHONK with the changes :)

**Comment by SuperUserNameMan** [comment]
@victordiaz : Good work ! It works ! :-)
