### ISSUE TITLE
mqtt example in 1.30

### ISSUE THREAD

**Issue by 42loop** [victordiaz/PHONK-examples#11]
callbacks onConnect & onDisconnect don't exist,
has to be: onConnected & onDisconnected

**Comment by victordiaz** [comment]
The new api is migrated to use onConnect and onDisconnect so is more consistent with the rest of the API :)

I'm double checking the app and it works for me using onConnect and onDisconnect
Did you download PHONk from the Play Store or from Github?

**Comment by 42loop** [comment]
i am using the freshly built github version 1.3.0:
 TypeError: Cannot find function onConnect in object io.phonk.runner.apprunner.api.network.PMqtt@8a9f9da. (MQTT#18)

**Comment by 42loop** [comment]
sorry, my git pull did not work out

**Comment by victordiaz** [comment]
No worries! :)
Thx for checking it out!
