### ISSUE TITLE
Incoherent baudrate between arduino.ino and main.js

### ISSUE THREAD

**Issue by baptistelabat** [victordiaz/PHONK-examples#5]
The example examples/Peripherals/Serial Communication is not working as it, and the baudrate need to be changed (currently 9600 on arduino side, vs 19200 on js side).

**Comment by baptistelabat** [comment]
Correction proposed in #6

**Comment by victordiaz** [comment]
@baptistelabat thx for pointing it out :)
The changes will be included in the next release by the end of the week, thanks!
