### ISSUE TITLE
BluetoothLE example does not disconnect

### ISSUE THREAD

**Issue by txf-** [victordiaz/PHONK-examples#7]
Using a OnePlus 7 Pro on Android 10, communicating with an ESP32. 

Trying to use the BLE example, when attempting to disconnect by toggling the checkbox, the function seems to be called, but it silently fails and the app then reconnects to the device. 

This might be related but, I found that terminating the script be it via the phone or the IDE, the connections don't get terminated. 

as a quick hack __stop() method does the trick, presumably by terminating the client object.

**Comment by victordiaz** [comment]
Thanks for reporting the issue. I'll have a look :)

**Comment by victordiaz** [comment]
This is fixed here [https://github.com/victordiaz/PHONK/commit/5710394f1ca36a3368a1340a7966877a42d51a5a](https://github.com/victordiaz/PHONK/commit/5710394f1ca36a3368a1340a7966877a42d51a5a)

It will be included in the next release

**Comment by victordiaz** [comment]
@txf- This should be fixed in 1.2.8. Feel free to try it out and check if it works. Thanks!

**Comment by txf-** [comment]
Alright, I'll see if I can try it out this weekend.

**Comment by victordiaz** [comment]
I close the issue since I haven't found the issue anymore. Feel free to reopen it if it does not work for you :)
