### ISSUE TITLE
LIBPD example : STOP/PLAY buttons are swapped

### ISSUE THREAD

**Issue by SuperUserNameMan** [victordiaz/PHONK-examples#9]
Hello,

With 1.2.8 on android 5.1 and 9, I've just noticed the STOP and PLAY buttons are swapped into the LIBPD example.

**Comment by victordiaz** [comment]
Oh, thx!
I did a big change inside how the views are placed and styled, so some errors were probably added too :/ I'll have a look!

**Comment by victordiaz** [comment]
Closing, since this issue was resolved in a previous release.
